/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BookIdImport } from './routes/$bookId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BookIdRoute = BookIdImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$bookId': {
      id: '/$bookId'
      path: '/$bookId'
      fullPath: '/$bookId'
      preLoaderRoute: typeof BookIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$bookId': typeof BookIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$bookId': typeof BookIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$bookId': typeof BookIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$bookId'
  id: '__root__' | '/' | '/$bookId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookIdRoute: typeof BookIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookIdRoute: BookIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$bookId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$bookId": {
      "filePath": "$bookId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
