/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BooksBookIdSlugImport } from './routes/books.$bookId.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookIdSlugRoute = BooksBookIdSlugImport.update({
  id: '/books/$bookId/$slug',
  path: '/books/$bookId/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookId/$slug': {
      id: '/books/$bookId/$slug'
      path: '/books/$bookId/$slug'
      fullPath: '/books/$bookId/$slug'
      preLoaderRoute: typeof BooksBookIdSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$bookId/$slug': typeof BooksBookIdSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$bookId/$slug': typeof BooksBookIdSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/books/$bookId/$slug': typeof BooksBookIdSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$bookId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books/$bookId/$slug'
  id: '__root__' | '/' | '/books/$bookId/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksBookIdSlugRoute: typeof BooksBookIdSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksBookIdSlugRoute: BooksBookIdSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books/$bookId/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books/$bookId/$slug": {
      "filePath": "books.$bookId.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
